// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  datasource: {
    url: "file:./dev.db",
  },
  models: {
    User: "User",
    ProductCategory: "ProductCategory",
    Product: "Product",
    ProductOption: "ProductOption",
    Order: "Order",
    OrderItem: "OrderItem",
    OrderStatusHistory: "OrderStatusHistory",
    OrderOption: "OrderOption",
  },
});